# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    binary: knot
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/oxgrad/knot/cmd.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64

archives:
  - formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

release:
  prerelease: auto
  make_latest: "{{ not .Prerelease }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

homebrew_casks:
  - name: knot
    skip_upload: "{{ .Prerelease }}"
    repository:
      owner: oxGrad
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/oxGrad/knot"
    description: "A lightweight, configurable dotfiles manager"
    license: MIT
  - name: knot-nightly
    skip_upload: "{{ not .Prerelease }}"
    repository:
      owner: oxGrad
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/oxGrad/knot"
    description: "A lightweight, configurable dotfiles manager"
    license: MIT
